### Get all categories
GET http://localhost:3000/categories/89bc9512-5d34-4b72-a106-ae4ac2d41be7 HTTP/1.1

### Create a new task
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Test",
  "description": "Test",
  "categoryId": "8a7f86a6-754d-49dc-8bb6-648f1bd2fe18"
}


### create cat
POST http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

{
  "name": "New Category"
}


