### Get all categories
GET http://localhost:3000/categories HTTP/1.1

### Get on category
GET http://localhost:3000/categories/3cc3b27e-4a61-41cb-846b-6b978c5bfe37 HTTP/1.1

### Create a new task
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "Dua",
  "description": "kids",
  "categoryId": "3cc3b27e-4a61-41cb-846b-6b978c5bfe37"
}


### create a new category
POST http://localhost:3000/categories HTTP/1.1
Content-Type: application/json

{
  "name": "bio"
}

### delete a category
DELETE http://localhost:3000/categories/31b698e0-8120-41e8-a7d2-955f057623b0

### delete task
DELETE http://localhost:3000/tasks/1892bc07-457b-40fb-8c30-dac32e2c3553


### get all tasks
GET  http://localhost:3000/tasks HTTP/1.1

### get one task
GET  http://localhost:3000/tasks/b635b865-bb27-46d3-bbc0-3b41e0f1098a HTTP/1.1
